ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'TRUCK_14FT';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'TRUCK_17FT';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'TRUCK_20FT';
ALTER TYPE "VehicleType" ADD VALUE IF NOT EXISTS 'CONTAINER_32FT';
