import { OrganizationRole } from '../enums/membership.enum';
import { Capability } from '../value-objects/capability.vo';

export class CapabilityResolver {
  static resolve(role: OrganizationRole): Capability[] {
    const caps: string[] = [];
    switch (role) {
      case OrganizationRole.PRIMARY_OWNER:
        caps.push(
          'VIEW_MEMBERS', 'INVITE_MEMBERS', 'CHANGE_MEMBER_ROLE', 
          'SUSPEND_MEMBER', 'REACTIVATE_MEMBER', 'REMOVE_MEMBER', 
          'TRANSFER_OWNERSHIP', 'MANAGE_SETTINGS', 'VIEW_REPORTS',
          'CREATE_BRANCH', 'UPDATE_BRANCH', 'ARCHIVE_BRANCH', 'VIEW_BRANCH', 'LIST_BRANCHES',
          'CREATE_DEPARTMENT', 'UPDATE_DEPARTMENT', 'ARCHIVE_DEPARTMENT', 'VIEW_DEPARTMENT', 'LIST_DEPARTMENTS',
          'CREATE_TEAM', 'UPDATE_TEAM', 'ARCHIVE_TEAM', 'VIEW_TEAM', 'LIST_TEAMS',
          'CREATE_DESIGNATION', 'UPDATE_DESIGNATION', 'ARCHIVE_DESIGNATION', 'VIEW_DESIGNATION', 'LIST_DESIGNATIONS',
          'CREATE_EMPLOYMENT_TYPE', 'UPDATE_EMPLOYMENT_TYPE', 'ARCHIVE_EMPLOYMENT_TYPE', 'VIEW_EMPLOYMENT_TYPE', 'LIST_EMPLOYMENT_TYPES',
          'CREATE_EMPLOYMENT_ASSIGNMENT', 'ASSIGN_EMPLOYMENT_TYPE', 'TRANSITION_EMPLOYMENT_ASSIGNMENT', 'VIEW_ASSIGNMENT_TIMELINE', 'VIEW_EMPLOYMENT_HISTORY',
          'CREATE_SCHEDULE_TEMPLATE', 'PUBLISH_SCHEDULE_VERSION', 'ASSIGN_SCHEDULE', 'RESOLVE_SCHEDULE', 'MANAGE_SCHEDULE_TEMPLATES',
          'GENERATE_SHIFT', 'OVERRIDE_SHIFT', 'VIEW_SHIFT'
        );
        break;
      case OrganizationRole.ORG_ADMIN:
        caps.push(
          'VIEW_MEMBERS', 'INVITE_MEMBERS', 'CHANGE_MEMBER_ROLE', 
          'SUSPEND_MEMBER', 'REACTIVATE_MEMBER', 'REMOVE_MEMBER', 
          'MANAGE_SETTINGS', 'VIEW_REPORTS',
          'CREATE_BRANCH', 'UPDATE_BRANCH', 'ARCHIVE_BRANCH', 'VIEW_BRANCH', 'LIST_BRANCHES',
          'CREATE_DEPARTMENT', 'UPDATE_DEPARTMENT', 'ARCHIVE_DEPARTMENT', 'VIEW_DEPARTMENT', 'LIST_DEPARTMENTS',
          'CREATE_TEAM', 'UPDATE_TEAM', 'ARCHIVE_TEAM', 'VIEW_TEAM', 'LIST_TEAMS',
          'CREATE_DESIGNATION', 'UPDATE_DESIGNATION', 'ARCHIVE_DESIGNATION', 'VIEW_DESIGNATION', 'LIST_DESIGNATIONS',
          'CREATE_EMPLOYMENT_TYPE', 'UPDATE_EMPLOYMENT_TYPE', 'ARCHIVE_EMPLOYMENT_TYPE', 'VIEW_EMPLOYMENT_TYPE', 'LIST_EMPLOYMENT_TYPES',
          'CREATE_EMPLOYMENT_ASSIGNMENT', 'ASSIGN_EMPLOYMENT_TYPE', 'TRANSITION_EMPLOYMENT_ASSIGNMENT', 'VIEW_ASSIGNMENT_TIMELINE', 'VIEW_EMPLOYMENT_HISTORY',
          'CREATE_SCHEDULE_TEMPLATE', 'PUBLISH_SCHEDULE_VERSION', 'ASSIGN_SCHEDULE', 'RESOLVE_SCHEDULE', 'MANAGE_SCHEDULE_TEMPLATES',
          'GENERATE_SHIFT', 'OVERRIDE_SHIFT', 'VIEW_SHIFT'
        );
        break;
      case OrganizationRole.HR:
        caps.push(
          'VIEW_MEMBERS', 'INVITE_MEMBERS', 'CHANGE_MEMBER_ROLE', 
          'SUSPEND_MEMBER', 'REACTIVATE_MEMBER', 'REMOVE_MEMBER', 
          'VIEW_REPORTS', 'VIEW_BRANCH', 'LIST_BRANCHES',
          'CREATE_DEPARTMENT', 'UPDATE_DEPARTMENT', 'VIEW_DEPARTMENT', 'LIST_DEPARTMENTS',
          'CREATE_TEAM', 'UPDATE_TEAM', 'ARCHIVE_TEAM', 'VIEW_TEAM', 'LIST_TEAMS',
          'CREATE_DESIGNATION', 'UPDATE_DESIGNATION', 'ARCHIVE_DESIGNATION', 'VIEW_DESIGNATION', 'LIST_DESIGNATIONS',
          'CREATE_EMPLOYMENT_TYPE', 'UPDATE_EMPLOYMENT_TYPE', 'ARCHIVE_EMPLOYMENT_TYPE', 'VIEW_EMPLOYMENT_TYPE', 'LIST_EMPLOYMENT_TYPES',
          'CREATE_EMPLOYMENT_ASSIGNMENT', 'ASSIGN_EMPLOYMENT_TYPE', 'TRANSITION_EMPLOYMENT_ASSIGNMENT', 'VIEW_ASSIGNMENT_TIMELINE', 'VIEW_EMPLOYMENT_HISTORY',
          'CREATE_SCHEDULE_TEMPLATE', 'PUBLISH_SCHEDULE_VERSION', 'ASSIGN_SCHEDULE', 'RESOLVE_SCHEDULE', 'MANAGE_SCHEDULE_TEMPLATES',
          'GENERATE_SHIFT', 'OVERRIDE_SHIFT', 'VIEW_SHIFT'
        );
        break;
      case OrganizationRole.SUPERVISOR:
      case OrganizationRole.EMPLOYEE:
        caps.push('VIEW_MEMBERS', 'VIEW_REPORTS', 'VIEW_DEPARTMENT', 'LIST_DEPARTMENTS', 'VIEW_TEAM', 'LIST_TEAMS',
          'VIEW_DESIGNATION', 'LIST_DESIGNATIONS');
        break;
      case OrganizationRole.VIEWER:
        caps.push('VIEW_REPORTS', 'LIST_BRANCHES', 'VIEW_DEPARTMENT', 'LIST_DEPARTMENTS', 'VIEW_TEAM', 'LIST_TEAMS',
          'VIEW_DESIGNATION', 'LIST_DESIGNATIONS');
        break;
    }
    return caps.map(c => new Capability(c));
  }
}
